# Generated by Django 3.1 on 2020-08-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('demoday', '0002_video_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
    ]
